import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import localFont from 'next/font/local'
import "./globals.css";
import 'swiper/css';
import 'swiper/css/free-mode';
import NavContainer from "./components/home/navbar/NavContainer";

const helveticaNeue = localFont({
  src:[
    {
      path: '/fonts/HelveticaNeue-Light.otf',
      weight: '200',
      style: 'light',
    },
    {
      path: '/fonts/HelveticaNeue-Regular.otf',
      weight: '400',
      style: 'normal',
    },
    {
      path: '/fonts/HelveticaNeue-Medium.otf',
      weight: '600',
      style: 'medium',
    },
    {
      path: '/fonts/HelveticaNeue-Bold.otf',
      weight: '800',
      style: 'medium',
    },
  ],
  display: 'swap', // 'swap' ensures text is visible while the font loads
  variable: '--font-helvetica-neue',
})

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${helveticaNeue.className} ${geistMono.variable} antialiased `}
      >
        {/* <NavContainer /> */}
        {children}
      </body>
    </html>
  );
}
